<?php

/**
 * @file
 * Contains dispatcher.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Entity\EntityInterface;
use Drupal\dispatcher\Util\Util;

/**
 * Implements hook_help().
 */
function dispatcher_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the dispatcher module.
        case 'help.page.dispatcher':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Dispatches text messages') . '</p>';
            return $output;

        default:
    }
}
/**
 * Implements hook_cron().
 */
function dispatcher_cron() {
    //log to dblog
    \Drupal::logger('dispatcher')->notice('sending out message now');
    $dispatcher = Drupal::service('dispatch.manager');
    //replace $$$$ with number you want to send message to
    $dispatcher->sendMessage('Say hello to my friend', '$$$$$$$$$');
}

/**
 * Implements hook_entity_insert
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function dispatcher_entity_insert(EntityInterface $entity) {

    $dispatcherConfig = Drupal::service('config.factory')->getEditable('dispatcher.config');
    $bundle = $entity->bundle();
    $contentType = $dispatcherConfig->get('content_type');

    if (strcmp($contentType, $bundle) == 0){
        $messageField = $dispatcherConfig->get('message_field');
        $message = $entity->get($messageField)->getValue();

        $recipientFields = $dispatcherConfig->get('recipient_field');

        $fields = array();
        foreach ($recipientFields as $recipientField){
            if ($recipientField != '0'){
                $fields[$recipientField] = $entity->get($recipientField)->getValue()[0]['target_id'];
            }
        }
        $numbers = getRecipientNumbers($fields);

        $dispatcher = Drupal::service('dispatch.manager');
        foreach ($numbers as $number){
            $results = $dispatcher->sendMessage($message[0]['value'], $number);
        }
        Drupal::service('messenger')->addMessage(json_encode($results));
    }
}
//@todo relocate to own service and create probably custom module to house it
function getRecipientNumbers($fields = array()){

    $numbers = array();
    $userStorage = \Drupal::service('entity_type.manager')->getStorage('user');
    $query = $userStorage->getQuery();
    $group = $query->orConditionGroup();

    foreach ($fields as $key => $field){
        $group->condition($key, $field);
    }

    $ids = $query->condition($group)->execute();
    $users = $userStorage->loadMultiple($ids);
    foreach ($users as $user){
        $name = $user->getUsername();
        if ($name != '0'){
            array_push($numbers, intVal($name));
        }
    }
    return $numbers;
}
