<?php

/**
 * @file
 * Contains dispatcher.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dispatcher_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dispatcher module.
    case 'help.page.dispatcher':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dispatches text messages') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_cron().
 */
function dispatcher_cron() {
    //log to dblog
    \Drupal::logger('dispatcher')->notice('sending out message now');
    $dispatcher = Drupal::service('dispatch.manager');
    //replace asterisk with number you want to send message to
    $dispatcher->sendMessage('Say hello to my friend', '$$$$$$$$$');
}
